receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  otlp/dash0:
    endpoint: ${env:DASH0_ENDPOINT}
    headers:
      Authorization: "Bearer ${env:DASH0_AUTH_TOKEN}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/dash0]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/dash0]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/dash0]
